// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://casroknzdishifjrwkit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhc3Jva256ZGlzaGlmanJ3a2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODc0NzUsImV4cCI6MjA2OTk2MzQ3NX0.JUcrit1iBoD6FkPRz6Ua1BctZPul8QefG3-fONKO_K0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});